### ISSUE TITLE
db_name/last_seq on on_change docs

### ISSUE THREAD

**Issue by lostnet** [redgeoff/spiegel#1]
## Problem for my intended usage:

It is not clear to me how/why an **on_change** doc becomes limited to a single target database such that it can track a last_seq on it. (This might be because it is not clear what the target of the **on_change**'s regex, while I think a **filter** regex is targeting the _global_changes update.)

In my usage, I need to write a single **on_change** that applies to all databases of a type where my database types are indicated in the db_name. Therefore, I would not want the system to add a db_name and last_seq to the **on_change** doc that I create.

## Alternate design that might work for more usages:
If all **on_changes** can be pushed to advance the same on a db, then I think the **Change Listener** could have a last_seq.

If on_changes are allowed to proceed at independently on the same db, then I think the **CL Service** could generate/update **on_change_instance** docs with the last_seq, db and a reference to the unmodified **on_change** template. Then an **onChange Service** could either listen on _global_changes for db updates and run each **on_change_instance** that matches the db to bring it up to the latest sequence **or** be watching for **on_change_instance** docs marked dirty by a replicator.

Does this make any sense?

**Comment by redgeoff** [comment]
You are right! My actual implementation for CouchDB 1 has the seq_num and
db_name in the change_listener. I'll move that over.

The regex in the on_change doc is for matching on DB name as you may want
the on_change to apply to a single DB, group of DBs or all DBs. I'll make a
note in the doc.

**Comment by redgeoff** [comment]
https://github.com/redgeoff/spiegel/pull/2
