### ISSUE TITLE
CouchDB 2.1 scheduler

### ISSUE THREAD

**Issue by endyjasmi** [redgeoff/spiegel#105]
Hello, cool project you have there. Currently experimenting with the scalable listener. One thing that I noticed is since CouchDB 2.1 introduces scheduler. I think it solve the same problem as spiegel replicator.

May I know what is the differences between the two?

**Comment by redgeoff** [comment]
Great question! I'm planning on doing a detailed writeup on this soon. For now, the summary is that you'll want to use Spiegel if you have a lot of databases, e.g. over 500, and only have a select segment of these databases changing at any given time. The new _replicator scheduler in CouchDB 2.1 is really cool, but it:
1. Is not yet intelligent enough to only replicate the databases that are changing. So, if you have 10,000 databases and only say 100 are changing at any given time then it will still try to replicate all 10,000 databases. This leads to a lot of latency if you are expecting the 100 active databases to receive timely replications.
2. This scheduler uses a round robin selection, which means that it can take a long time for the replicator to randomly select the segment of databases (say the 100) that you are really interested in.
The CouchDB team is planning to enhance the _replicator scheduler in the future by adding an option that will make it only replicate those databases that are changing, but this work is not yet scheduled so it is hard to say when it will be ready.

**Comment by endyjasmi** [comment]
@redgeoff Thanks for prompt reply. You cleared of the question in my head.
