### ISSUE TITLE
Change listener doesn't handle a deleted source database 

### ISSUE THREAD

**Issue by sc0ttdav3y** [redgeoff/spiegel#112]
Hi again!

In my application we run a per-user database model where we create and destroy CouchDB databases from time to time as user accounts are created and destroyed.

I've noticed that whenever a CouchDB database is deleted, the Spiegel update listener picks up the change (in this case, that the database is deleted), but then the Spiegel change listener continuously retries to process that database but fails with a "Database does not exist" exception.

I believe it should detect that error condition and remove the associated record from the ```spiegel``` couchdb database to prevent continuous retries, in the same way that it correctly detects the creation of a new CouchDB database and adds the record.

Here's an excerpt from the logs with the backtrace.  This is on ```v.1.0.3``` but was also occurring on older versions.

Thanks again for the great work on Spiegel.

```
{
"name": "spiegel",
"hostname": "47d7445f206c",
"pid": 6,
"level": 50,
"err": {
"message": "reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]",
"name": "Error",
"stack": "Error: reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]\nat EnhancedRequest._newError (/usr/local/lib/node_modules/spiegel/node_modules/couch-slouch/scripts/enhanced-request.js:84:11)\nat /usr/local/lib/node_modules/spiegel/node_modules/couch-slouch/scripts/enhanced-request.js:150:18\nat tryCatcher (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/util.js:16:23)\nat Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:512:31)\natPromise._settlePromise (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:569:18)\nat Promise._settlePromise0 (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:614:10)\nat Promise._settlePromises (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:693:18)\nat Promise._fulfill (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/promise.js:638:18)\nat Request._callback (/usr/local/lib/node_modules/spiegel/node_modules/bluebird/js/release/nodeback.js:42:21)\nat Request.self.callback (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:186:22)\nat Request.emit (events.js:160:13)\nat Request.<anonymous> (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:1163:10)\nat Request.emit (events.js:160:13)\nat IncomingMessage.<anonymous> (/usr/local/lib/node_modules/spiegel/node_modules/request/request.js:1085:12)\nat Object.onceWrapper (events.js:255:19)\nat IncomingMessage.emit (events.js:165:20)"
},
"msg": "reason=Database does not exist., error=not_found, arguments=[{\"url\":\"http://admin:xxxxxxx@couchdb:5984/source-db/_changes\",\"qs\":{\"since\":\"45-g1AAAAIbeJyV0M0NgjAYBuDGnwAHZ9ARaAuFnmQT7Q8ECZaDetZNdBPdRDfB0pJgNCT10iZf-j5t3xoA4JdTCRaqUY3MM9WUzeFY6_GEAb5s27Yqp2y-1wMP4QLTsPg-PBLnK73ydS8AI8SQYEG4BMFJybzYqVyOpbMuvenTgUmneYRhQl3v33bCuRc8IwhYREmEHAU10yu46E0j107xjcJgiCB07cEqN6vchy4E5SER1KELKzys8Bx-kzAkSAr_esfLKh-txoISjH-U6g3dpqNg\",\"include_docs\":true,\"limit\":1},\"parseBody\":true}]",
"time": "2018-02-12T05:21:12.370Z",
"src": {
"file": "/usr/local/lib/node_modules/spiegel/src/process.js",
"line": 309,
"func": "_onError"
},
"v": 0
}
```

**Comment by redgeoff** [comment]
There is indeed a design issue in Spiegel with the case where you delete databases. As you mentioned, the current functionality is for Spiegel to keep retrying the change-listener. Unfortunately, I don't think it is as simple as just detecting this _not_found_ error and then removing the change-listener as CouchDB is eventually consistent so I would imagine that you can expect to sometimes get these _not_found_ errors normally when the change-listener and target database is simultaneously created--I believe it can take time for the database to be created by all nodes in your cluster.

Instead, I think the easiest solution would be to use the updated_at in the change-listener doc to determine if the change-listener should be deleted, e.g. if a _not_found_ error is encountered and the if it has been say 5 minutes since the change-listener was updated, delete the change-listener.

@sc0ttdav3y want to take a stab a creating a PR for this?

**Comment by redgeoff** [comment]
@sc0ttdav3y any progress on this?

**Comment by sc0ttdav3y** [comment]
@redgeoff I’m currently on other non-couchdb/spiegel work but will look again in a few weeks. This one may be a bit beyond my understanding of Spiegel’s architecture though, so I’ll take a fresh look if it’s still outstanding soon, but I may not be comfortable in solving it.

**Comment by redgeoff** [comment]
Sounds good. Let me know if you need some help
