### ISSUE TITLE
Replication Filters

### ISSUE THREAD

**Issue by ephopper** [redgeoff/spiegel#118]
Could you provide some detail as to how to use the filter property of the replicator docs? I wasn't able to find anything in the docs about it, other than that it is available to use. 

I tried different variations of mango style selectors as well as simple regex statements, but all caused the replicators to error and be retried many times before I was finally able to delete the docs.

**Comment by redgeoff** [comment]
Hi @ephopper! I don't believe you can use mango selectors with [filtered replication](http://docs.couchdb.org/en/2.1.1/api/server/common.html#replicate). Instead, I think you need to use views or filters defined in design docs.

I've added more documentation that shows an [example of filtered replication](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#replicator) with Spiegel.

**Comment by ephopper** [comment]
Hi @redgeoff, Thanks for the information! That answers my question!

a note about mango selectors - they aren't shown in the api, but here is an example of using them for filtered replication when POSTing to the `/_replicate` endpoint:

```
curl - X POST http: //localhost:5984/_replicate -d '{"source": "http://localhost:5984/testdb1", "target": "http://localhost:5984/testdb3", "selector": {"_id": {"$regex": "^someDoc"}}}' -H Content-Type:application/json -u username:password 


{
    "ok": true,
    "session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "source_last_seq": "9-xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "replication_id_version": 4,
    "history": [
    {
        "session_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "start_time": "Sat, 28 Apr 2018 19:53:33 GMT",
        "end_time": "Sat, 28 Apr 2018 19:53:35 GMT",
        "start_last_seq": 0,
        "end_last_seq": "9-xxxxxxxxxxxxxxxxxxxxxxxxxx",
        "recorded_seq": "9-xxxxxxxxxxxxxxxxxxxxxxxxxx",
        "missing_checked": 4,
        "missing_found": 4,
        "docs_read": 4,
        "docs_written": 4,
        "doc_write_failures": 0
    }]
}
```
this successfully sets up a one-shot replication of all docs in testdb1 whose _id starts with `someDoc` to testdb3

I've also been using mango selectors for filtered replication with continuous and one-shot replicators in `/_replicator` docs for about a year now. I found the couch documentation to be lacking on this point and pretty much only discovered this through experimentation.

Thanks!

**Comment by redgeoff** [comment]
Interesting! If the selectors work for the _replicator endpoint then they
will work in Spiegel.

**Comment by ephopper** [comment]
When I tried previously, the replicators kept failing/retrying. I tried different versions of the above selector and couldn't get it to work though. 

I'm guessing my syntax might have been incorrect for passing the selector through spiegel then. I'll try a few more things and see if I can get it to work.

Thanks!

**Comment by ephopper** [comment]
looks like the issue was me trying to make the selector the value of the filter property instead of having the selector be the top level property. But this works:
```
{
  "_id": "testdb1_to_testdb4_8",
  "type": "replicator",
  "source": "http://admin@localhost:5984/testdb1",
  "target": "http://admin@localhost:5984/testdb4",
  "selector":{"_id":{"$regex":"^someDoc"}}
}
```

**Comment by redgeoff** [comment]
Cool!
