### ISSUE TITLE
Question: PouchDB implementation

### ISSUE THREAD

**Issue by ephopper** [redgeoff/spiegel#127]
I've been testing Spiegel on the backend and it seems to work out pretty well for what I'm doing. I'm developing a mobile app and was wondering about the feasibility of creating a "frontend" version that works with Pouch that I could use client-side.
Have you looked into anything like that at all?

In looking through some of the code, it seems that both Spiegel and Slouch are looking for the `_global_changes` database specifically. Would it be enough to create a Pouch version of that DB that mimics the functionality of the Couch version?

Thanks!

**Comment by redgeoff** [comment]
Interesting idea! The global_changes feed is pretty specific to CouchDB so
it may take a lot of work to recreate something like this in the browser.

As for Spiegel itself, it’s definitely doable as I believe all the
dependencies, except spawn, also work in the browser. All in all though I
think it would take a significant amount of work to set it up and test it
and this isn’t the direction that I’d like to take Spiegel. If you do end
up working on a fork that runs in the browser then I can give you some tips.

In general, can you describe more as to why you’d want to run Spiegel in
the front end and not the backend? You can definitely use PouchDB in the
frontend and Spiegel in the backend today—we did that for Quizster.

**Comment by ephopper** [comment]
Hi @redgeoff , 
The idea was actually to try and use Spiegel on both the frontend and the backend if possible. In my testing on the backend so far, it seems to work great - thus my curiosity for use on the frontend. 

As to the why:
We're developing a mobile app that uses Pouch on the client to sync the user's DB's with those on the Couch backend. There may be multiple DB's that the user is subscribed to, so we were wanting to get away from having to have a bunch of change listeners and continuous replicators running all the time and work toward something that is more event driven.

**Comment by redgeoff** [comment]
The way that we handled the listening to multiple DBs from the client was
using https://github.com/redgeoff/couchdb-howler and then only syncing when
there is a change for a specific DB.

**Comment by ephopper** [comment]
Looks Interesting! 
I'll look into it a bit deeper and see if it will work for us. I may be asking you some questions over there too then ;)

Thanks!
