### ISSUE TITLE
Passwords are not injected in replication handler requests

### ISSUE THREAD

**Issue by tudordumitriu** [redgeoff/spiegel#132]
We are running the replicator service with the following command:
spiegel --type="replicator" --url="http://sa:**@192.168.0.127:5984" --passwords-file="replicator-passwords.json" --log-level="info" | bunyan

If we are not including the admin pass in the replication documents URLS (which should work I guess) replication is not working and it throws the following error:
Could not open source database `http://sa@192.168.0.127:5984/central/`: {unauthorized,<<"http://sa@192.168.0.127:5984/central/">>}, error=not_found, arguments=[{"url":"http://sa:**@192.168.0.127:5984/_replicate","method":"POST","json":{"_id":"4481ca1b2334349b4467eb37b9ac9143","_rev":"1537-6873335c4eb7c62eb8c5d4a36988ff27","source":"http://sa@192.168.0.127:5984/central","target":"http://sa@192.168.0.127:5984/userdb-7a","filter":"centralReplication/userFilter","query_params":{"sharedTo":"org.couchdb.user:z"}}}]

Running CouchDB 2.1.1 on Windows 10

**Comment by redgeoff** [comment]
Hi @tudordumitriu! On the surface it looks like this should work, but from the error you can see that no password has been injected, which means that Spiegel didn't find any corresponding password. I'd check the path to your `replicator-passwords.json`--I think you may need an absolute path.

Also, to be clear your `replicator-passwords.json` needs to be something like
```
{
  "192.168.0.127": {
    "sa": "yourpassword"
  }
}
```

**Comment by tudordumitriu** [comment]
Thanks 
I was using the url not just the host
