### ISSUE TITLE
Updating filter design docs while Spiegel processes are running stops replication permanently

### ISSUE THREAD

**Issue by tudordumitriu** [redgeoff/spiegel#136]
As the title says if we update design doc filters while processes are running causes the Spiegel db replication records to became dirty: true and locked_at: timestamp which I think might be the cause for stopping replication permanently.

Updating the fields in Speigel db docs manually and restarting the processes will restart the replication, but otherwise nothing can be done.

This is kind of nasty because there is absolutely no clue why the replication is not working. We just had to try everything and this is how we found this.

OS: Windows 10
CouchDB: 2.1.1
Speigel: 1.0.3

**Comment by redgeoff** [comment]
Hey @tudordumitriu! The replications will be restarted automatically. There is a routine that periodically checks for stalled processes and then retries them. This routine will retry the replications indefinitely. (You can read more about it in the [replicator](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#replicator) and [Replicator Proceses](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#replicator-processes) design)

Also, in general, the replication shouldn't fail in the first place unless there was a transient error or something is incorrectly configured. If it is incorrectly configured then it will continue to fail each time it is retried. I'd suggest taking a look at the log for details as to why a replication is failing.

**Comment by tudordumitriu** [comment]
Hi and thanks @redgeoff 
What is the retry interval? 
Because we waited for few mins and nothing happen

**Comment by redgeoff** [comment]
Currently, the default for [retryAfterSeconds is 10800](https://github.com/redgeoff/spiegel/blob/master/bin/usage.txt#L75) and [checkStalledSeconds is 600](https://github.com/redgeoff/spiegel/blob/master/bin/usage.txt#L90) and it will take roughly checkStalledSeconds + retryAfterSeconds before an action is retried.

As for the second part of your question, yes, please split it out into a separate issue.

**Comment by tudordumitriu** [comment]
Thanks
