### ISSUE TITLE
assume-deleted-after functionality does not actually work

### ISSUE THREAD

**Issue by jjd314** [redgeoff/spiegel#147]
I fooled myself when testing it by starting the change-listener many minutes after all the docs had been marked as dirty, so the _getAndDestroy branch in _processAndUnlockIfError was immediately taken.  If the dirty flag gets set during the normal course of events, the _isProbablyDeleted() call fails, and the else branch in taken.  The _upsertUnlock ends up changing the updated_at field, and the assume-deleted-after threshold is never reached.  I'm working on a fix.

**Comment by redgeoff** [comment]
I think the solution may be something like https://github.com/redgeoff/spiegel/pull/144#issuecomment-408170736
