### ISSUE TITLE
Question: PouchDB <-> CouchDB live sync in scale

### ISSUE THREAD

**Issue by elgutierrez** [redgeoff/spiegel#164]
Hello,

First of all, I would like to thank you for your article about how to run a CouchDB cluster in production using AWS, it was really helpful. 

I'm developing an app that is already using PouchDB and storing the data offline, and we're going to deploy a CouchDB server so we can back up the user's data on the cloud. We are using the db-per-user architecture and Superlogin for user authentication, and it seems to work pretty well. 

My questions concern the live sync between CouchDB and CouchDB in a prod environment, with many users. We have currently ~7000 users and we are a bit concerned about the performance and how CouchDB would behave with hundreds/thousands of users Live Synching theirs DBs at the same time? Have you ever had this experience? Do you have some feedback?

**Comment by redgeoff** [comment]
Hey Rafael, I think you are probably going to run into issues live syncing
7k DBs using CouchDB’s built-in replicator. It will work, but you’ll have
to allocate a ton of file handles to keep all the streams open. Instead,
I’d recommend using Spiegel and creating a replicator doc per DB. This
solution will scale a lot better.

**Comment by redgeoff** [comment]
Actually, your post also mentions live syncing PouchDB and CouchDB and that
is a bit of a different beast. In this case I’d recommend using
https://github.com/redgeoff/couchdb-howler and an on-demand sync as it will
scale better than having a dedicated feed per client.

**Comment by elgutierrez** [comment]
I don't really get how `couchdb-howler` interacts with pouchdb, nor what you mean by on-demand sync. Could you explain a little further?

**Comment by redgeoff** [comment]
Well, the details on what I recommend depend on your data.

1. It sounds like each client/app is only syncing with a single DB, right?

2. How many of these users will be using the app concurrently? Is it all
7k? Is this number likely to grow?

**Comment by elgutierrez** [comment]
1. We are using the `db-per-user` architecture, so yes, each user is synching with their on DB. We're planning to have a CouchDB Cluster (3 instances at the beginning) + Loadbalancer

2. We don't expect to have 7k concurrent users right now (most likely 500 now), but it could become a reality soon if we have a successful product :) It could even go further, we never know...

I'm also taking a look at WebSockets instead of HTTP for the transport layer so we have less overhead. What do you think?

**Comment by redgeoff** [comment]
1. I asked this because in my experience, I'd often had to use a hybrid version of a db-per-user and also a db-per-group, as this allows more users to share data. This essentially means that a single client is listening to multiple DBs and this makes things more complicated as a browser has a limited amount of connections that it can hold simultaneously. Fortunately, your use-case is more simple ;)

Well, I'd definitely recommend using web sockets to cut down on the traffic. I haven't used [socket-pouch](https://github.com/pouchdb-community/socket-pouch), but it may help you get there quicker.

I think for your use case, I'd recommend just using live syncing directly from PouchDB to CouchDB and just bumping up [max_dbs_open](http://docs.couchdb.org/en/stable/config/couchdb.html#couchdb/max_dbs_open) and [allowed number of file handles](https://stackoverflow.com/questions/41103624/emfile-error-running-couchdb-on-ubuntu-16). This will probably get you there the fastest and you should be able to just add more CouchDB nodes to keep up with any increasing demand.

**Comment by redgeoff** [comment]
Hey @regner!

I think it would help if I dig in a little deeper as to why you would need [couchdb-howler](https://github.com/redgeoff/couchdb-howler). couchdb-howler allows you to subscribe to CouchDB global changes in a scalable way. The native way to get a list of changes is to listen to the _global_changes feed on the CouchDB. This, however; requires a dedicated connection and can be costly if you have multiple clients listening for global changes. Instead, a couchdb-howler instance maintains a single _global_changes feed and then reports changes to its subscribing clients.

So, why would you need couchdb-howler? The main reason I developed it is that in [Quizster](https://quizster.co) a single client can listen to a bunch of different databases simultaneously. For example, a teacher listens to all the student's databases for a change in work. To make this efficient, Quizster uses couchdb-howler to wait for a change on a specific database and then does an on-demand sync between PouchDB and CouchDB. The alternative would be to have the PouchDB instances continuously listen to the CouchDB databases and this would be VERY wasteful and wouldn't work as the browser only allows a limited amount of open connections.

Quizster listens to multiple databases as this is a way of side-stepping the need to replicate a ton of extra data, e.g. a student can generate a lot of work and if all her/his work were to be replicated to the teacher's database then the teacher's database would become huge. Huge databases take a long time to replicate and using filter functions on these large databases is super slow.

If your design is basic db-per-user, where the client is only listening to a single database, I recommend that you just bump up [max_dbs_open](http://docs.couchdb.org/en/stable/config/couchdb.html#couchdb/max_dbs_open) and [allowed number of file handles](https://stackoverflow.com/questions/41103624/emfile-error-running-couchdb-on-ubuntu-16). This solution is easy and should scale well.

Spiegel, on the other hand, is something that you would use on the back end. In your case, I think you may need it to perform real-time syncing of your clusters. Specifically, you can use Spiegel and create a [replicator doc](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#replicator) for each database that will replicate the database when that database changes.
