### ISSUE TITLE
on_change support $variables in the url's path similar to parameters

### ISSUE THREAD

**Issue by lostnet** [redgeoff/spiegel#171]
Currently, on_change supports $ variables in parameters:
```
 url: '<api-url>', // e.g. https://user@api.example.com. Passwords maintained via
                    // passwords config

  // Parameters passed to API call
  params: {
    change: '$change'   // can use $change for change doc
    db_name: '$db_name' // $db_name is the name of matching DB
  },
```
Which then end up as query parameters or in the data sent depending on the request type.

But I would like to support existing APIs that are variable on other url components, for example couchdb's update design documents:

```
 url: 'http://admin@othercouch:5984/${db_name}/_design/designdoc/_update/updateFun/${changeid}',

  // Parameters passed to API call
  params: {
    change: '$change' 
    seq: '$seq'
  },
  method: 'POST',
```

I think the [_buildParams
](https://github.com/redgeoff/spiegel/blob/master/src/change-processor.js#L45) parameters could be essentially the same for rewriting variables parsed out of  the url, but the parsing of the url may require more separable variable names i.e. ${variable} instead of $variable.

**Comment by redgeoff** [comment]
Hey @lostnet! I think this would be a great enhancement. Like you state, we should be able to reuse the same logic in buildParams to set variables in the URL string. Would you be willing to work on a PR?

The big gotcha right now is that something changed in one of spiegel’s deps so the tests are broken on CircleCI—it appears to be a race condition and I just haven’t had time to look into it yet.

**Comment by lostnet** [comment]
Hi @redgeoff, I put together a PR with the method I was thinking of and a unit test. I get some failures whether or not I am using my changes at "spiegel->integration->should replicate and listen to changes" which I think are the problems breaking CircleCI?

**Comment by redgeoff** [comment]
Implemented by https://github.com/redgeoff/spiegel/pull/173
