### ISSUE TITLE
 throw when an API status code is not 200 ignores that all 2xx responses are valid

### ISSUE THREAD

**Issue by lostnet** [redgeoff/spiegel#177]
Existing APIs such as [couchdb's update](https://docs.couchdb.org/en/2.2.0/api/ddoc/render.html#db-design-design-doc-update-update-name-doc-id) send other 2xx response codes for results such as a 201 Created, as per the [spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2)

I think spiegel is waiting for the response event, so there is no need to consider 1xx events and it is safe to do:
`
      if (response && response[0] && response[0].statusCode >= 300) {
`
but it could also checked for both bounds of success [200,300)

**Comment by redgeoff** [comment]
Nice catch! I think checking for >=200 && <400 would be best.

**Comment by lostnet** [comment]
On 3xx response codes my thinking is that request is either handling them for us and replacing the code or it is a 3xx where spiegel would need to do something but doesn't? I.e they are errors if we see them. But I haven't really done anything to test how request works with redirects exactly..

**Comment by redgeoff** [comment]
Yeah, I don’t have any experience with 300-level codes so that would also
work for me

**Comment by lostnet** [comment]
I'd like to test some other APIs in the next weeks and one of them uses 3xx redirects regularly but it uses GET so if I understand the follow section in the [request README](https://github.com/request/request) it will happen automatically and the 2nd response will work with the 2xx coverage.

It seems like there are a few situations for 3xx on other methods where it might be impossible to determine if the processing requires following the redirect or it already occurred and the redirect is just UI. It might be necessary to pass request settings for its redirect function if anyone needs that..

On couchdb's update API, I've tested that these changes in conjunction with the url variables are sufficient. I'm not sure if it makes sense to open another issue for 3xx, or let someone find this issue and open it when they have an example API and situation where they occur?

**Comment by redgeoff** [comment]
I think this sounds like a good plan!

**Comment by redgeoff** [comment]
@lostnet any chance in creating a PR for this (with a test)?

**Comment by lostnet** [comment]
@redgeoff I did some investigation into web apis starting with mailgun. Aside from this issue I'd like to:
1. add support for explicitly specifying data format (i.e. formData) for those who can't use the default [json](https://github.com/redgeoff/spiegel/blob/master/src/change-processor.js#L107)
2. add support for $change.vars generalizing beyond the [id/rev support](https://github.com/redgeoff/spiegel/pull/173/commits/018ce6f12d2ad017fb89a94eb3d8a22e97b086ef)

Looking at koa, I think I can add the necessary routes on the test/api-server for full test coverage. If that makes sense and you have time to review them, I can go through these one issue/PR at a time?

**Comment by redgeoff** [comment]
Sounds good. One PR at time is best :)
