### ISSUE TITLE
Change Listening service to external API?

### ISSUE THREAD

**Issue by bgold0** [redgeoff/spiegel#178]
I'm attempting to create a Scalable Change Listening service that I can look for changes made to my database and then send that these changes to an external API (not couchdb)

I'm not quite sure in the documentation where it shows how to do this. It seemed like this is possible in the explanation you gave but everything I see in the documentation references couchdb url's. 

Could anyone provide more context if this is possible?

**Comment by redgeoff** [comment]
Hi @bgold0! You’d want to use an [on_change](https://github.com/redgeoff/spiegel/blob/master/DESIGN.md#on_change) doc
