### ISSUE TITLE
Spiegel could use design documents for better efficiency/reuse

### ISSUE THREAD

**Issue by lostnet** [redgeoff/spiegel#3]
In [DBUpdatesListener Service](https://github.com/redgeoff/spiegel#dbupdateslistener-service) Step 2, spiegel is listening on the **_global_changes** feed and then running every update through its own form of "filter" documents.

Looking for ways to combine this with design document usage

## Standard Filter/view Design for _changes feeds

If a design document were added to the **_global_changes** as a standard  _design/ (filter or view) then a spiegel **DBUpdatesListener** would only need to be notified when a relevant database is called and the design/capability of its filtering would expand naturally with any improvements made in couchdb to **_global_changes** or standard design documents. This could also then be applied to a databases other than the **_global_changes** to derive databases to mark as `dirty:true`.

I think this same method and a design document in the spiegel database itself could then handle the **ChangesListener**'s observation of its CL docs.

```
// Example of both views (though they exist in their respective databases):
{ 
  id:"_design/spiegel",
  language: "javascript",
  views: {
   globalrelevantsview: {
    map: "function(doc) {
     if (!doc.key)
       return;
     if (/created:myprefix/.test(doc.key))
        emit(/:(.*)$/.exec(doc.key))[1]);
    }"
   },
   spiegelrelevantsview: {
     map: "function(doc) {
       if (!doc.type || doc.type != 'change_listener')
         return;
       if (doc.dirty == true)
         emit(doc.dbname);
     }"
  }
 }
}
```

## Spiegel specific Designs
I think this could be extended by adding a new design document type to handle the specifics of spiegel's observer stages in its model of externals_observer->internal_doc->internal_observer->(internal_doc->)spiegel_action, with something like:

```
// Example of design document to configure a permanent feed Observer:
// ${db} = _global_changes|_spiegel|?
{ 
  id:"_design/change_observer..",
  feed: "${db}/_changes?since=cache${db}.last_seq&heartbeat=true&filter=_view&view=spiegel/[global|spiegel]relevantsview"
 // Perhaps spiegel specific functions like:
  language: "javascript",
  spiegel_find_or_create_internal_docs: "function(update) {...}",
  spiegel_update_internal_docs: "function(update, internal_docs) {...}"
 // or TBD interface to spiegel onchange and replicator
}
```

**Comment by redgeoff** [comment]
@lostnet thanks for the awesome feedback!

1. Your idea to use a design doc for the `filter` (which I just renamed to `sieve` to prevent confusion with actual CouchDB filters) is a great one! The referenced PR has the change.

2. My existing implementation actually uses a view to find the dirty CLs so I just made a note in the design to reflect this detail.

3. Your idea on the `Spiegel specific designs` looks cool, but if I understand it correctly, I think it is a little out of the scope of what I'd like to accomplish with Spiegel. The idea is to keep Spiegel as simple as possible and offload almost all of the real logic to a RESTful API that Spiegel calls to actually get the work done. This way, Spiegel can be scaled quite easily and the configuration isn't overwhelming.

**Comment by lostnet** [comment]
Thank you @redgeoff ! I like the changes you've made for system filters on global changes and describing the ones you use in the CL system. ( I'm working on implementing the cross-user behavior for a similar system, but my users are peers which provides a symmetry that keeps me worried I will generate cascading feedback loops if my filtering is incomplete or too late to prevent itself from generating new to be filtered changes, etc. )

With `Spiegel specific designs` my thinking is that if Spiegal is mostly design docs that could live in a db that is both its and a replicators then over time it would mostly become tweakable JS responsible for generating temporary docs that act as instructions with the replicator eventually taking over responsibility for the new infrastructure like changes feeds, RESTful API calls, etc.
