### ISSUE TITLE
Backoff when replication or API request error

### ISSUE THREAD

**Issue by redgeoff** [redgeoff/spiegel#69]
Should a construct be added so that an exponential backoff occurs when there is a replication or API request error? Currently, when an error is encountered, Spiegel will put the item back in the queue and retry it. This is fine when the errors are transient and ideally all these errors would be transient, but if the error is permanent then Spiegel will _waste_ significant resources until the error can be resolved.

It may be ideal to implement the [dirty_after_milliseconds](https://github.com/redgeoff/spiegel/issues/53) enhancement first so that it can be used here

**Comment by jjd314** [comment]
Even worse for me is that the spiegel_cl_xxx document for the database in question gets continually updated.  If there is a real problem and the API is unavailable for a few hours, it can easily fill the disk that the spiegel database is on.  An exponential backoff would prevent that, and if it is recorded in the spiegel_cl_xxx document, as I imagine it would be, one could create a view on the spiegel database to monitor for stuck listeners.

**Comment by redgeoff** [comment]
Agreed. PRs are welcome and I can help if you are interested in submitting a PR ;)

**Comment by jjd314** [comment]
Sure, I'll give it a shot.  I don't know how much time I have for it, but I'll try to keep it moving along.  My guess is that the ChangeProcessor will have to somehow return information about the backoff to the ChangeListener so it can be written into the on_change doc.  I'm thinking that I will make two changes to the ChangeListener (besides recording the backoff): if there is a backoff reported, I'll have to add some sort of timer to try it again; and if another change comes in during the backoff, I'll have to queue it up for retrying after the timeout.  Does that sound reasonable, or is there some better place to put this stuff?

**Comment by redgeoff** [comment]
Well, I think the key to making this enhancement is that you need to worry about multiple instances of the services, e.g. ChangeListener and also need to account for services being restarted, added, etc... In other words, the state of whether the item needs to be retried needs to reside in the DB and not in the memory of a single service. So, I think implementing the enhancement at https://github.com/redgeoff/spiegel/issues/53 should be first as it will then provide a scalable construct for dirtying an on_change or replicator after a given set of time.

**Comment by jjd314** [comment]
Great.  It's a twofer.  I'll take a look at #53 first, then.

**Comment by jjd314** [comment]
I just submitted a pull request for #53.  I'm going to assume that it will eventually get merged, and I'm starting work on this based off of that code.  I have a couple of questions:
1. What are reasonable initial and max backoff times?  I'm thinking of starting at 500ms and doubling it each time until a max of 1 hour.
2. Should those values be customizable?  If so, should they be global parameters, or should it be per on-change document?
3. I'm no longer sure I can use the dirty_at mechanism from #53 for this: dirty_at is on a change_listener, but you could have several on_change documents, only one of which is having trouble with its API call.  Am I misreading something?

**Comment by redgeoff** [comment]
1. I think that sounds reasonable
2. I think as global parameters is a good place for now. It would be easy to change this in the future.
3. I think the best thing for now is to manage the retrying on on_changes via the change_listener, i.e. somewhere like https://github.com/redgeoff/spiegel/blob/master/src/change-listeners.js#L239 you can  set dirty_at for the CL and not update the seq num on the CL. This would result in _pausing_ all the on_changes for the CL, but I think this is probably acceptable. The alternative is to have a CL per on_change and that would greatly increase complexity and latency.

**Comment by bleachy** [comment]
Hi @redgeoff - I know this is an old repo but would like to get the PR above merged in if thats still possible? We're using Spiegel currently and although rare, we'd like to have more control over the frequency of the failed API requests when they're replayed.

I'd appreciate any time you can give this. Thanks 🙏

**Comment by redgeoff** [comment]
🚀 Thanks for the hard work, @bleachy!
