### ISSUE TITLE
spiegel not working (Database does not exist)

### ISSUE THREAD

**Issue by ysidheshwar** [redgeoff/spiegel#73]
- I have tried to install spiegel using npm install -g spiegel  this is executed successfully by referring 
  following link [](https://github.com/redgeoff/spiegel/blob/master/README.md) .
- Then i tried to install spiegel database using this command 
  spiegel \--type='install' \  --url='http://user:password@yourcouchdb.com:5984' with my couchdb username  password and url And i can see spiegel database in my couchdb but i got the following error on terminal :-
`{"name":"spiegel","hostname":"merce-ThinkPad-T410s","pid":30279,"level":50,"err":{"message":"reason=Database does not exist., error=not_found","name":"Error","stack":"Error: reason=Database does not exist., error=not_found\n at CouchPersistentStreamIterator._onceData (/home/suyog/.npm-global/lib/node_modules/spiegel/node_modules/couch-slouch/scripts/couch-persistent-stream-iterator.js:18:22)\n at Request.<anonymous> (/home/suyog/.npm-global/lib/node_modules/spiegel/node_modules/quelle/scripts/persistent-stream-iterator.js:83:16)\n at Object.onceWrapper (events.js:316:30)\n at emitOne (events.js:120:20)\n at Request.emit (events.js:210:7)\n at IncomingMessage.<anonymous> (/home/suyog/.npm-global/lib/node_modules/spiegel/node_modules/request/request.js:1082:12)\n at emitOne (events.js:115:13)\n at IncomingMessage.emit (events.js:210:7)\n at IncomingMessage.Readable.read (_stream_readable.js:478:10)\n at flow (_stream_readable.js:849:34)\n at resume_ (_stream_readable.js:831:3)\n at _combinedTickCallback (internal/process/next_tick.js:138:11)\n at process._tickCallback (internal/process/next_tick.js:180:9)"},"msg":"reason=Database does not exist., error=not_found","time":"2017-12-07T06:14:08.337Z","src":{"file":"/home/suyog/.npm-global/lib/node_modules/spiegel/src/update-listeners.js","line":73,"func":"_оnError"},"v":0}
`
- Even on running following command i face the same above error
 $ spiegel \  --type='update-listener' \ --url='http://user:password@yourcouchdb.com:5984'
  for creating update-listener  process .
- Kindly help.

**Comment by redgeoff** [comment]
If you definitely see the `spiegel` database then I think you may be missing the `_global_changes` database.

I've also created https://github.com/redgeoff/slouch/issues/57 to add a more descriptive error as these generic errors have been bugging me for a while :D

**Comment by redgeoff** [comment]
I've just released [v0.1.0](https://github.com/redgeoff/spiegel/releases/tag/v0.1.0) which adds more details to the errors. There is also an accompanying Docker image.

**Comment by redgeoff** [comment]
Closing as no response from @ysidheshwar and latest version should provide more error info
