### ISSUE TITLE
Replicator is not working after it has run once 

### ISSUE THREAD

**Issue by ssd532** [redgeoff/spiegel#82]
I have a simple replicator document. Currently, it looks like following:

```
{
  "_id": "_design/repl-test2-test3",
  "_rev": "20-bf00529e57870dd442eeb26a57fa059d",
  "type": "replicator",
  "source": "http://localhost:5984/test2",
  "target": "http://localhost:5984/test3",
  "dirty": false,
  "locked_at": null,
  "updated_at": "2017-12-28T11:10:16.041Z"
}
```

I have observed that the replication happens only once. After that `dirty` flag never changes to true even after making changes in the source database. If I set it to `true` manually, then again the database is replicated immediately.

I tried to dig down into the source code and have found following.

- To dirty the replicators `dirtyIfCleanOrLocked(dbNames)` is called which calls `_attemptToDirtyIfCleanOrLocked(dbNames)` which then calls `_getCleanOrLocked(dbNames)`
- `_getCleanOrLocked(dbNames)` gets the list of dirty replicators by invoking following code

```
    let response = await this._slouch.db.viewArray(
      this._spiegel._dbName,
      '_design/clean_or_locked_replicators_by_db_name',
      'clean_or_locked_replicators_by_db_name',
      { include_docs: true, keys: JSON.stringify(dbNames) }
    )
    return response.rows.map(row => row.doc)
```
- `clean_or_locked_replicators_by_db_name` is following:

```
function(doc) {
    if (doc.type === "replicator" && doc.source && (!doc.dirty || doc.locked_at)) {
        var i = doc.source.lastIndexOf("/");
        if (i !== -1) {
            emit(doc.source.substr(i + 1), null);
        }
    }
}
```

Now, I may be missing something but there are no non-design documents in `spiegel` database which have `type: replicator`. There are change listeners for each database like spiegel_cl_test1, spiegel_cl_test2, spiegel_cl_test3 etc They all have `type: change_listener`. But I do not have any such document with `type: replicator`.

Have I misunderstood something or missed any step or does it look like some bug?

**Comment by redgeoff** [comment]
I think the issue is that you need to place the replicator docs in the
spiegel database and not the replicator database.

**Comment by ssd532** [comment]
I can confirm that the replicator doc is in spiegel database only. Anyhow if the replicator document is not in spiegel database the replication will not work even once, right? Replication works when I set it to `true` manually. 

Could you give me some pointer on how `dirty` flag is set to true in the replicator document when a change happens in the source database? I can dig down further. Thanks.

**Comment by ssd532** [comment]
`clean_or_locked_replicators_by_db_name` view in spiegel database with following definition

```
function(doc) {
    if (doc.type === "replicator" && doc.source && (!doc.dirty || doc.locked_at)) {
        var i = doc.source.lastIndexOf("/");
        if (i !== -1) {
            emit(doc.source.substr(i + 1), null);
        }
    }
}
```
which is being referred in `_getCleanOrLocked(dbNames)` -- I am assuming is to get the list of replicators where `dirty` is `false` -- suggests that there has to be some non-design document in spiegel database with `type` field set to `replicator`. There are such documents present for change-listeners e.g. I have documents spiegel-cl-test1, spiegel-cl-test2 and spiegel-cl-test3 with field `replicator: change_listener`. But there isn't any doc with `type: replicator`. 

Due to the absence of any document with `type: replicator` view `clean_or_locked_replicators_by_db_name` always returns an empty array and the dirty flag is never reset to true. 

BTW in the source code of `change-listener`, I found that change-listener documents for each database are created with a separate namespace adding a prefix called `spiegel_cl_`. But there is no such implementation in `replicator.js`.

**Comment by ssd532** [comment]
It just clicked :)

The replicator document should not be a design document, right? Now when I created the replicator document as a regular document, it is working as expected. I was assuming wrong things all along. 

When I had tried change-listeners, I had created them as design documents, and they were working fine. Hence I created replicators also as ddocs. It seems I need to relook at change-listeners as well. :)

**Comment by redgeoff** [comment]
Ahh... that explains it! Thanks. I’ll add some documentation for this.

**Comment by redgeoff** [comment]
Ahh... that explains it! Thanks. I’ll add some documentation for this as yes, the replicator docs should not be design docs. Therefore, the ids of the replicator docs should be anything that doesn't start with `_design/`

The change_listeners are automatically created and maintained by Spiegel according to the `on_change` docs that you have created so you shouldn't have to worry about the ids of the change_listeners. (The ids of the change_listeners are prefixed with `spiegel_cl_` so that you can have a change_listener for a system database like the `_users` database).
